[package]
name = "efficiency_calc"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
blackjack_lib = {path = "../blackjack_lib"}